"""Init DB

Revision ID: 20d128dd5cc0
Revises: 
Create Date: 2026-06-30 19:24:34.379842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d128dd5cc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stok',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produk_id', sa.Integer(), nullable=True),
    sa.Column('jumlah', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produk_id'], ['produk.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produk_id')
    )
    op.create_table('stok_harian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produk_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('keterangan', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['produk_id'], ['produk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('penjualan', schema=None) as batch_op:
        batch_op.alter_column('tanggal',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('total_bayar',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('bayar')
        batch_op.drop_column('tipe_pesanan')
        batch_op.drop_column('kembalian')
        batch_op.drop_column('meja_id')

    with op.batch_alter_table('penjualan_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('harga_satuan', sa.Integer(), nullable=False))
        batch_op.alter_column('penjualan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('produk_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('subtotal')
        batch_op.drop_column('laba')
        batch_op.drop_column('harga_jual')
        batch_op.drop_column('catatan')

    with op.batch_alter_table('produk', schema=None) as batch_op:
        batch_op.alter_column('kategori',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               nullable=False)

    with op.batch_alter_table('resep', schema=None) as batch_op:
        batch_op.drop_column('nama_resep')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resep', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_resep', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('produk', schema=None) as batch_op:
        batch_op.alter_column('kategori',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('penjualan_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catatan', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('harga_jual', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('laba', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('subtotal', sa.INTEGER(), nullable=True))
        batch_op.alter_column('produk_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('penjualan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('harga_satuan')

    with op.batch_alter_table('penjualan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meja_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('kembalian', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('tipe_pesanan', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('bayar', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'meja', ['meja_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_bayar',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('tanggal',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    op.drop_table('stok_harian')
    op.drop_table('stok')
    # ### end Alembic commands ###
