"""Tambah tabel pengaturan

Revision ID: 37555997236c
Revises: dfcf459e5d39
Create Date: 2026-07-17 03:54:03.898692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37555997236c'
down_revision = 'dfcf459e5d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pengaturan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_toko', sa.String(length=100), nullable=True),
    sa.Column('alamat', sa.String(length=255), nullable=True),
    sa.Column('no_telp', sa.String(length=20), nullable=True),
    sa.Column('mata_uang', sa.String(length=10), nullable=True),
    sa.Column('pajak_persen', sa.Float(), nullable=True),
    sa.Column('service_charge_persen', sa.Float(), nullable=True),
    sa.Column('catatan_struk', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pengaturan')
    # ### end Alembic commands ###
