"""tambah tabel racikan, racikan_detail, dan kolom racikan_id di resep_detail
Revision ID: 40ff47bcccc6
Revises: 2dc144667581
Create Date: 2026-07-20 06:30:05.281265
"""
from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision = '40ff47bcccc6'
down_revision = '2dc144667581'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('racikan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_racikan', sa.String(length=100), nullable=False),
    sa.Column('satuan_hasil', sa.String(length=20), nullable=True),
    sa.Column('porsi_hasil', sa.Integer(), nullable=True),
    sa.Column('harga_per_porsi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('racikan_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('racikan_id', sa.Integer(), nullable=False),
    sa.Column('bahan_id', sa.Integer(), nullable=False),
    sa.Column('qty_pakai', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bahan_id'], ['bahan_baku.id'], ),
    sa.ForeignKeyConstraint(['racikan_id'], ['racikan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resep_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('racikan_id', sa.Integer(), nullable=True))
        batch_op.alter_column('bahan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_resep_detail_racikan_id', 'racikan', ['racikan_id'], ['id'])
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resep_detail', schema=None) as batch_op:
        batch_op.drop_constraint('fk_resep_detail_racikan_id', type_='foreignkey')
        batch_op.alter_column('bahan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('racikan_id')
    op.drop_table('racikan_detail')
    op.drop_table('racikan')
    # ### end Alembic commands ###