"""tambah metode_bayar di buku_kas

Revision ID: 7fe6ba746222
Revises: 40ff47bcccc6
Create Date: 2026-07-22 03:42:26.025008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe6ba746222'
down_revision = '40ff47bcccc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buku_kas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metode_bayar', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buku_kas', schema=None) as batch_op:
        batch_op.drop_column('metode_bayar')

    # ### end Alembic commands ###
