"""Initial migration with revised models

Revision ID: da5d8067138a
Revises: 
Create Date: 2026-07-04 01:21:44.599634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5d8067138a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bahan_baku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=20), nullable=True),
    sa.Column('nama_bahan', sa.String(length=100), nullable=False),
    sa.Column('satuan', sa.String(length=20), nullable=True),
    sa.Column('harga_beli_terakhir', sa.Integer(), nullable=True),
    sa.Column('stok', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.Column('no_hp', sa.String(length=20), nullable=True),
    sa.Column('tipe', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor_meja', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomor_meja')
    )
    op.create_table('produk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=20), nullable=True),
    sa.Column('nama_produk', sa.String(length=100), nullable=False),
    sa.Column('kategori', sa.String(length=30), nullable=False),
    sa.Column('harga_jual', sa.Integer(), nullable=False),
    sa.Column('harga_beli', sa.Integer(), nullable=True),
    sa.Column('harga_beli_supplier', sa.Integer(), nullable=True),
    sa.Column('is_konsinyasi', sa.Boolean(), nullable=True),
    sa.Column('gambar', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('penjualan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('total_bayar', sa.Integer(), nullable=False),
    sa.Column('bayar', sa.Integer(), nullable=True),
    sa.Column('kembalian', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('meja_id', sa.Integer(), nullable=True),
    sa.Column('tipe_pesanan', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['meja_id'], ['meja.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produk_id', sa.Integer(), nullable=True),
    sa.Column('porsi_hasil', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produk_id'], ['produk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buku_kas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('penjualan_id', sa.Integer(), nullable=True),
    sa.Column('jenis', sa.String(length=20), nullable=True),
    sa.Column('keterangan', sa.String(length=200), nullable=True),
    sa.Column('jumlah', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['penjualan_id'], ['penjualan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hutang_supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('produk_id', sa.Integer(), nullable=False),
    sa.Column('penjualan_id', sa.Integer(), nullable=False),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('qty_laku', sa.Integer(), nullable=True),
    sa.Column('total_hutang', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['penjualan_id'], ['penjualan.id'], ),
    sa.ForeignKeyConstraint(['produk_id'], ['produk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meja_penjualan',
    sa.Column('meja_id', sa.Integer(), nullable=False),
    sa.Column('penjualan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meja_id'], ['meja.id'], ),
    sa.ForeignKeyConstraint(['penjualan_id'], ['penjualan.id'], ),
    sa.PrimaryKeyConstraint('meja_id', 'penjualan_id')
    )
    op.create_table('penjualan_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('penjualan_id', sa.Integer(), nullable=True),
    sa.Column('produk_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('harga_satuan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['penjualan_id'], ['penjualan.id'], ),
    sa.ForeignKeyConstraint(['produk_id'], ['produk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resep_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resep_id', sa.Integer(), nullable=False),
    sa.Column('bahan_id', sa.Integer(), nullable=False),
    sa.Column('qty_pakai', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bahan_id'], ['bahan_baku.id'], ),
    sa.ForeignKeyConstraint(['resep_id'], ['resep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resep_detail')
    op.drop_table('penjualan_detail')
    op.drop_table('meja_penjualan')
    op.drop_table('hutang_supplier')
    op.drop_table('buku_kas')
    op.drop_table('resep')
    op.drop_table('penjualan')
    op.drop_table('users')
    op.drop_table('produk')
    op.drop_table('meja')
    op.drop_table('customer')
    op.drop_table('bahan_baku')
    # ### end Alembic commands ###
