"""Tambah kolom is_ready ke penjualan_detail

Revision ID: dfcf459e5d39
Revises: da5d8067138a
Create Date: 2026-07-12 03:05:29.427115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfcf459e5d39'
down_revision = 'da5d8067138a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penjualan_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ready', sa.Boolean(), nullable=True))
        batch_op.alter_column('penjualan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('produk_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penjualan_detail', schema=None) as batch_op:
        batch_op.alter_column('produk_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('penjualan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('is_ready')

    # ### end Alembic commands ###
