"""tambah metode_bayar ke penjualan

Revision ID: e9729b459ab4
Revises: b1772917226c
Create Date: 2026-07-18 18:10:53.434050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9729b459ab4'
down_revision = 'b1772917226c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penjualan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metode_bayar', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penjualan', schema=None) as batch_op:
        batch_op.drop_column('metode_bayar')

    # ### end Alembic commands ###
